---
# CLI Variables setup.

- name: Define php_cli_memory_limit.
  set_fact:
    php_cli_memory_limit: "{{ php_memory_limit }}"
  when: php_cli_memory_limit is not defined

- name: Define php_cli_max_execution_time.
  set_fact:
    php_cli_max_execution_time: "{{ php_max_execution_time }}"
  when: php_cli_max_execution_time is not defined

- name: Define php_cli_max_input_time.
  set_fact:
    php_cli_max_input_time: "{{ php_max_input_time }}"
  when: php_cli_max_input_time is not defined

- name: Define php_cli_max_input_vars.
  set_fact:
    php_cli_max_input_vars: "{{ php_max_input_vars }}"
  when: php_cli_max_input_vars is not defined

- name: Define php_cli_realpath_cache_size.
  set_fact:
    php_cli_realpath_cache_size: "{{ php_realpath_cache_size }}"
  when: php_cli_realpath_cache_size is not defined

- name: Define php_cli_date_timezone.
  set_fact:
    php_cli_date_timezone: "{{ php_date_timezone }}"
  when: php_cli_date_timezone is not defined

- name: Define php_cli_short_open_tag.
  set_fact:
    php_cli_short_open_tag: "{{ php_short_open_tag }}"
  when: php_cli_short_open_tag is not defined

- name: Define php_cli_error_reporting.
  set_fact:
    php_cli_error_reporting: "{{ php_error_reporting }}"
  when: php_cli_error_reporting is not defined

- name: Define php_cli_display_errors.
  set_fact:
    php_cli_display_errors: "{{ php_display_errors }}"
  when: php_cli_display_errors is not defined

- name: Define php_cli_display_startup_errors.
  set_fact:
    php_cli_display_startup_errors: "{{ php_display_startup_errors }}"
  when: php_cli_display_startup_errors is not defined

- name: Define php_cli_expose_php.
  set_fact:
    php_cli_expose_php: "{{ php_expose_php }}"
  when: php_cli_expose_php is not defined
