---
- name: cassandra-php | install build dependencies
  apt:
    name: "{{ php_cassandra_php_driver_build_dependencies }}"
    state: present

- name: cassandra-cpp | ensure cassandra c++ driver is not installed
  find:
    paths: /usr/lib/x86_64-linux-gnu/
    recurse: true
    patterns: '*cassandra*'
  register: cassandra_cpp_result

- name: cassandra-cpp | install cassandra c++ driver and dependencies
  include_tasks: _download_install.yml
  loop: "{{ php_cassandra_cpp_driver_dependencies_pkgs + php_cassandra_cpp_driver_pkgs }}"
  when: cassandra_cpp_result.matched < 1

- name: cassandra-php | check for cassandra php driver
  shell:
    cmd: /usr/bin/php{{ php_default_version_debian }} -m | grep 'cassandra'
  failed_when: false
  changed_when: false
  register: php_cassandra_check_install

- name: cassandra-php | download and compile cassandra php driver if it is not found
  block:
    - name: cassandra-php | Set working directory
      set_fact: 
        workdir: /usr/src/php-driver

    - name: cassandra-php | download datastax/php-driver from GitHub
      git: 
        repo: "{{ php_cassandra_php_driver_repo }}"
        version: "{{ php_cassandra_php_driver_version }}"
        dest: "{{ workdir }}"

    - name: cassandra-php | compile source code
      shell:
        cmd: |
          set -ex
          /usr/bin/phpize{{ php_default_version_debian }}
          mkdir -p {{ workdir }}/build
          cd {{ workdir }}/build
          ../ext/configure --with-php-config=/usr/bin/php-config{{ php_default_version_debian }} > /dev/null
          make clean >/dev/null
          make -j{{ ansible_processor_cores }}
          make install
          echo 'extension=cassandra.so' > /etc/php/{{ php_default_version_debian }}/mods-available/cassandra.ini
          phpenmod -v {{ php_default_version_debian }} cassandra
        chdir: "{{ workdir }}/ext"
        executable: /bin/bash

    - name: cassandra-php | cleanup
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ workdir }}"
      when: php_cassandra_php_driver_cleanup_build | bool
      
  when: php_cassandra_check_install.rc == 1
  tags: ['molecule-idempotence-notest']
