---
- name: pdo_dblib | install dependencies
  apt:
    name: "{{ php_pdo_dblib_driver_dependencies }}"
    state: present

- name: pdo_dblib | configure FreeTDS for pdo_dblib
  template: 
    src: "{{ php_pdo_dblib_driver_ini_template }}"
    dest: /etc/freetds/freetds.conf
    owner: root
    group: root
    mode: 0644

- name: pdo_dblib | install PHP extension
  apt:
    name: php{{ php_default_version_debian }}-sybase
    state: present
