---
- name: Ensure PHP packages are installed.
  yum:
    name: "{{ item }}"
    state: installed
    enablerepo: "{{ php_enablerepo }}"
  with_items: "{{ php_packages }}"
  register: php_package_install
  notify: restart webserver
