---
- name: restart webserver
  service:
    name: "{{ php_webserver_daemon }}"
    state: restarted
  notify: restart php-fpm
  when: php_enable_webserver

- name: restart php-fpm
  service:
    name: "{{ php_fpm_daemon }}"
    state: restarted
  when: php_enable_php_fpm

- name: systemd restart php-fpm
  systemd:
    name: "{{ php_fpm_daemon }}.service"
    daemon_reload: yes
    state: restarted
  when: php_enable_php_fpm
