---
- name: restart webserver
  service:
    name: "{{ php_webserver_daemon }}"
    state: restarted
  when: php_enable_webserver

- name: restart php5-fpm
  service:
    name: php5-fpm
    state: restarted
  when: php_enable_php_fpm
