---
- name: Converge
  hosts: instance
  become: yes

  pre_tasks:
    - name: Debug vars
      debug:
        msg:
          "php_cassandra_php_driver_repo": "{{ php_cassandra_php_driver_repo }}"

  vars:
    php_enable_webserver: false
    php_enable_php_fpm: true
    php_memory_limit: "192M"
    php_install_recommends: false
    php_pecl_extensions_install:
      - apcu
      - redis
    php_extensions_enable:
      - apcu
      - redis

  roles:
    - name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
