---
- name: Prepare
  hosts: instance
  become: yes

  handlers:
    - name: Update apt cache
      apt: 
        update_cache: true

  tasks:
    - name: Update apt cache.
      apt: 
        update_cache: true 
        cache_valid_time: 600

    - name: Ensure dirmngr is installed (gnupg dependency).
      apt:
        name: dirmngr
        state: present

    # Ubuntu-specific tasks.
    - name: Add Ondrej Sury's repo (Ubuntu).
      apt_repository: 
        repo: ppa:ondrej/php
        state: present
      notify: Update apt cache
      when: ansible_distribution == 'Ubuntu'

    # Debian-specific tasks.
    - name: Add ondrej repository for Debian
      block: 
        - name: Add dependencies for PHP versions (Debian).
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - gnupg2
            state: present

        - name: Add Ondrej Sury's apt key (Debian).
          apt_key:
            url: https://packages.sury.org/php/apt.gpg
            state: present

        - name: Add Ondrej Sury's repo (Debian).
          apt_repository:
            repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
            state: present
          notify: Update apt cache
      when: ansible_distribution == 'Debian'

    - name: Flush handlers
      meta: flush_handlers
