---
- name: Verify
  hosts: instance
  become: yes
  gather_facts: yes

  tasks:
    - name: Ensure cassandra compiled driver was installed
      shell:
        cmd: |
          set -o pipefail
          php -m | grep -qiE 'cassandra'
        executable: /bin/bash
      register: ext_cassandra
      changed_when: ext_cassandra.rc != 0
